github.com:
    user: d3m1sc0
    oauth_token: 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
    git_protocol: https
    users:
        d3m1sc0:
            oauth_token: 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
