
[env]
TERM = "xterm-256color"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_title = true
opacity = 1

[general]
import = [
    "~/.config/alacritty/themes/themes/carbonfox.toml"
]
